import re

def update_markdown():
    # Read original
    with open('report/final_report.md', 'r', encoding='utf-8') as f:
        text = f.read()

    # Shift headers 2..8 -> 3..9
    # Format of section headers in markdown: "## 2. Problem Formulation" or "### 2.1 State Space"
    lines = text.split('\n')
    new_lines = []
    
    section_pattern = re.compile(r'^(##+ )([2-8])(\..*)$')
    
    for line in lines:
        match = section_pattern.match(line)
        if match:
            prefix = match.group(1)
            num = int(match.group(2))
            suffix = match.group(3)
            new_lines.append(f"{prefix}{num + 1}{suffix}")
        else:
            new_lines.append(line)
            
    text_shifted = '\n'.join(new_lines)

    # Acoustics intro content
    acoustics_intro = """## 2. Introduction to Underwater Acoustics and Passive Detection

Underwater acoustic propagation is the primary modality for underwater sensing, communication, and target tracking. Electromagnetic waves (such as light and radio waves) suffer from extreme attenuation in saline water, leaving acoustic waves (which travel at approximately $c \\approx 1500$ m/s) as the only viable mechanism for long-range marine observation.

### 2.1 Passive Sonar and Spectrograms
Passive sonar systems listen to the sound radiated by targets without transmitting active pulses. The received time-domain pressure signal is converted to the time-frequency domain using the Short-Time Fourier Transform (STFT) to produce Low-Frequency Analysis and Recording (LOFAR) spectrograms. Within these spectrograms (as shown in Figure 2.1), target signatures manifest in two forms:
*   **Broadband Background Noise**: Continuous, non-stationary noise distributed flatly across the spectrum, generated by wave action, wind, thermal activity, and shipping traffic.
*   **Narrowband Tonals**: Highly concentrated horizontal lines generated by rotating machinery, engines, generators, and propeller blade rates. These tonals carry the unique acoustic signature of the vessel.

### 2.2 Physical Challenges of Acoustic Tracking
Acoustic vessel tracking is highly challenging due to several physical phenomena:
1.  **Doppler Frequency Drift**: When a vessel moves relative to the hydrophone, the observed frequency shifts:
    $$f_{\\text{observed}} = f_0 \\left( \\frac{c \\pm v_r}{c \\mp v_s} \\right)$$
    where $v_s$ and $v_r$ are the source and receiver velocities. During vessel acceleration or turning maneuvers, these shifts cause the tonals to "slide" across frequency bins.
2.  **Multipath Propagation & Echoes**: Acoustic waves reflect off both the sea surface and the seabed, creating multiple delayed paths. This results in parallel phantom tracks (multipath echoes) and harmonic overtones, as illustrated in Figure 2.1b.
3.  **Acoustic Fading (Doppler Nulls)**: Destructive interference from multipath propagation causes temporary signal drops, requiring the tracking system to maintain track coherence through periods of zero-amplitude detections.

<table style="width: 100%; border: none;">
  <tr style="border: none;">
    <td style="width: 60%; text-align: center; border: none; padding: 5px;">
      <img src="./images/LOFAR_Joint_Signal.png" style="width: 100%;" />
      <br>
      <em>Figure 2.1a: Raw LOFAR spectrogram showing overlapping vessel target signatures and ambient noise.</em>
    </td>
    <td style="width: 40%; text-align: center; border: none; padding: 5px;">
      <img src="./images/lofar_annotated.png" style="width: 100%;" />
      <br>
      <em>Figure 2.1b: Annotated LOFAR spectrogram showing base frequencies (green) and harmonics (orange/red).</em>
    </td>
  </tr>
</table>

---

"""

    # We want to replace the transition before "## 3. Problem Formulation"
    target_str = "---\n\n## 3. Problem Formulation"
    if target_str in text_shifted:
        text_shifted = text_shifted.replace(target_str, "---\n\n" + acoustics_intro + "## 3. Problem Formulation")
    else:
        text_shifted = text_shifted.replace("## 3. Problem Formulation", acoustics_intro + "## 3. Problem Formulation")

    # Replace the duplicate figure in Appendix A.2 with a cross-reference
    # In final_report.md, let's locate the table with LOFAR_Joint_Signal.png in Appendix A
    # Let's search and replace:
    pattern_app = re.compile(
        r'The comparison below displays the raw spectrogram alongside the annotated version marking key tonality elements:\s*<table.*?</table\s*>', 
        re.DOTALL
    )
    
    text_shifted = pattern_app.sub(
        'The raw and annotated spectrograms are displayed in Figure 2.1 in Section 2, marking key tonality elements.', 
        text_shifted
    )

    with open('report/final_report.md', 'w', encoding='utf-8') as f:
        f.write(text_shifted)

    print("Markdown report updated successfully!")

if __name__ == "__main__":
    update_markdown()
